function [fitresult, gof] = FitErfAndGaussianGFP(x, y)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 30-Oct-2019 16:48:09


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'b+(p0/2)*erf((x-x0)/(sqrt(2)*w0))+a1*exp(-((x-x0)/(2*w0))^2)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.DiffMinChange = 1e-06;
opts.Display = 'Off';
opts.Lower = [0.1 0 0 0 1];
opts.Robust = 'LAR';
opts.StartPoint = [0.5 0.716302635035789 0.48 0.8003 7];
opts.TolFun = 0.0001;
opts.TolX = 0.0001;
opts.Upper = [1 1 1 10 16];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
h = plot( fitresult, xData, yData );
legend('hide');
set(h, 'MarkerSize',30);


